version: '3.9'

services:
    db:
        image: postgres:latest
        container_name: db
        restart: unless-stopped
        env_file: .env
        environment:
            - POSTGRES_PASSWORD=$DB_PWD
            - POSTGRES_DB=$DB_NAME
        ports:
            - '$DB_PORT:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - psts
    app:
        container_name: app
        build:
            context: .
        ports:
            - 8000:8000
        depends_on:
            - db
        networks:
            - psts
        volumes:
            - .:/home/node/app/
volumes:
    pgdata:

networks:
    psts:
